# Use root/example as user/password credentials
version: '3.0'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  flask-app:
    build: 
      context: ./flask_app  # Directory containing the Flask Dockerfile
      dockerfile: Dockerfile  # This is optional if your file is named Dockerfile
    environment:
      - FLASK_ENV=development
    volumes:
      - ./flask_app:/flask-app
    ports:
      - 3001:5000
    depends_on:
      - mongo





