import './css/style.css'
import { Inter, Architects_Daughter } from 'next/font/google'
import Header from '@/components/ui/header'

// Defines the "Inter" font Configuration 
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

// Defines the "Architects_Daughter" font Configuration
const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
  display: 'swap'
})

// Metadata
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * Root Layout Component
 * @param {object} children - React children elements to render.
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased bg-gray-200 text-gray-900 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden">
          <Header /> {/* Render the Header component */}
          {children} {/* Render the children elements */}
        </div>
      </body>
    </html>
  )
}
 